---
title: "Phylogenetic Tree"
output: 
  html_notebook:
    css: style.css
    theme: paper
---

Load packages

```{r, message=FALSE}
library(tidyverse)
library(ggtree)
library(tidytree)
```

Load and combine data

```{r, message=FALSE}
data <- read_csv("../data/data.csv")  %>% group_by(species) %>% summarise(n = sum(n))
species <- read_csv("../data/species_data.csv") %>% select(-species)
tree <- read.nexus("../data/consensusTree_10kTrees_Primates_Version3.nex")
```

```{r}
# turn tree into tidy dataframe
tree2 <- as_tibble(tree)

# add variables
tree3 <- tree2 %>% 
  left_join(species, by = c("label" = "species_latin")) %>% 
  left_join(data, by = c("species_formatted" = "species"))

# turn back into tree
tree4 <- as.treedata(tree3)
```

Visualize

```{r}
# display node numbers for reference
ggtree(tree4) +
  geom_label(aes(label = node), size = 3) +
  geom_tiplab(aes(label = str_c('n = ', n, ' ', label)), offset = .02) +
  expand_limits(x = .7) +
  ggtitle("Node numbers")
```

```{r}
clade <- tibble(
  node = c(21, 20, 14, 17), 
  clade = c("Strepsirrhini", "Platyrrhini", "Catarrhini", "Hominidae")
  )

data2 <- tibble(
  node = 21:12,
  n = c(16, 64, 62, 67, 72, 20, 23, 96, 160, 176)
)
```

```{r}
tree3.2 <- tree3 %>% 
  mutate(label_selected = ifelse(node %in% c(7, 9, 4, 3), label, "")) %>% 
  left_join(clade) %>% 
  left_join(data2, by = "node") %>% 
  mutate(n = coalesce(n.x, n.y)) %>% 
  select(-n.x, -n.y) %>% 
  groupClade(c(21, 20, 14, 17))

tree5 <- as.treedata(tree3.2)
```

```{r, eval=FALSE}
# check sample sizes
ggtree(tree5) +
  geom_label(aes(label = n), size = 3) +
  geom_tiplab(offset = .02) +
  expand_limits(x = .7) +
  ggtitle("Sample sizes")
```

```{r}
ggtree(tree5, aes(col = group, size = n, alpha = n)) +
  # colored branches
  geom_tree() +
  geom_tree(col = "black", size = .3, alpha = 1) +
  # selected tip and branch labels
  geom_tiplab(aes(label = label_selected), offset = .02, col = "black", size = 3, alpha = 1) +
  geom_text(aes(x = branch, label = clade), col = "black", alpha = 1, size = 3, vjust = -1) +
  # tweak scales
  scale_color_viridis_d(end = .9) +
  scale_size_area() +
  scale_alpha_continuous(range = c(.3, .8)) +
  # make room for tip labels
  expand_limits(x = .65) #+
  # # add legend
  # guides(col = "none") +
  # theme(legend.position = "right")
```

```{r}
ggsave("../graphs/phylo.png", width = 8, height = 4)
```


```{r}
ggtree(tree5, aes(col = group, size = n, alpha = n), branch.length='none', layout='circular') +
  # colored branches
  geom_tree() +
  #geom_tree(col = "black", size = .3, alpha = 1) +
  # selected tip and branch labels
  geom_tiplab(aes(label = species_formatted, angle = angle), offset = .2, col = "black", size = 3, alpha = 1) +
  geom_text(aes(x = branch, label = clade), col = "black", alpha = 1, size = 3, vjust = -1) +
  # tweak scales
  scale_color_viridis_d(end = .9) +
  scale_alpha_continuous(range = c(.3, .8)) +
  # make room for tip labels
  expand_limits(x = .65) #+
  # # add legend
  # guides(col = "none") +
  # theme(legend.position = "right")
```

```{r}
ggsave("../graphs/phylo_fan.png", width = 5, height = 5)
```
