---
title: "Sites"
output:
  html_notebook:
    css: style.css
    theme: paper
---

```{r setup, message=FALSE}
library(tidyverse)
library(cowplot)
library(maps)
library(ggforce)
library(viridis)
library(ggtree)
library(ggthemes)
library(treeio)
library(tidytree)
library(grid)
```

```{r, message=FALSE}
studies <- read_csv("../data/studies_gsheet.csv")
species <- read_csv("../data/species_gsheet.csv")
fulltree <- read.nexus("../data/consensusTree_10kTrees_298Primates_V3.nex")
refs <- read_csv("../data/ref_nodes.csv")
```

```{r}
data <- studies %>% 
  left_join(species, by = c("species" = "species_file")) %>% 
  rename(label = species_tree, num = n) %>% 
  select(label, studyID, species, site, num)
```

```{r}
diversity <- data %>% 
  group_by(label,species) %>% 
  summarise(Nsites = n_distinct(site),
            Nstudies = n_distinct(studyID))%>%
  mutate(div_score = Nsites / Nstudies)
```

```{r}
div_tree1 <- fulltree %>%
  as_tibble%>%
  mutate(label = fct_recode(label, "Pan_troglodytes" = "Pan_troglodytes_verus",
                                   "Pongo_spp" = "Pongo_abelii")) %>% 
  left_join(diversity)

to_drop <- div_tree1 %>% filter(is.na(Nstudies) | Nstudies < 2) %>% pull(label)

div_tree2 <- as.treedata(div_tree1)

div_tree3 <- drop.tip(div_tree2, to_drop)
```

```{r}
ggtree(div_tree3, aes(color = div_score), layout = "circular")+
  geom_tree()+
  geom_tiplab2(offset = 3, size = 3)+
  #geom_tiplab(offset = 3, size = 3)+
  scale_color_gradient2(high = "#009E73", mid = "grey", low = "#E69F00", midpoint = .5, name = "#Sites / #Studies", limits = c(0,1))+
  guides(colour = guide_colourbar(title.position="top", title.hjust = 0.5))+
  xlim(NA, 100)+
  theme(legend.position = c(.9,.1),legend.direction = "horizontal")
  #theme(legend.position = c(.2,.8),legend.direction = "horizontal")
```

```{r, cache=TRUE}
ggsave("../graphs/diversity_circle.pdf", width = 8, height = 8, scale = 1)
```

```{r}
ggplot(diversity_2, aes(y = species, x = Nstudies))
  
```




***

# Session Info

```{r}
sessionInfo()
```
